nodeLinker: pnp

packageExtensions:
  'multer-s3@*':
    dependencies:
      '@aws-sdk/abort-controller': ^3.6.0
  'ts-loader@*':
    dependencies:
      webpack: ^5.76.3
  '@tiptap/starter-kit@*':
    dependencies:
      '@tiptap/pm': '^2.0.2'
  '@adminjs/design-system@*':
    dependencies:
      'prop-types': '^15.8.1'
      'react-is': '^18.2.0'
  'babel-plugin-styled-components@*':
    dependencies:
      '@babel/core': '7.22.5'
  '@adminjs/express@*':
    dependencies:
      'express': '^4.18.2'
      'tslib': '^2.5.3'
  '@nestjs-modules/mailer@*':
    dependencies:
      'lodash': '^4.17.21'
      'tslib': '^2.5.3'

pnpMode: strict

yarnPath: .yarn/releases/yarn-3.6.0.cjs
