version: '3.8'
services:
  api:
    image: 'omg-backend'
    build:
      context: ./
      dockerfile: ./Dockerfile
    entrypoint: ['yarn', 'start:prod']
    ports:
      - 8000
    networks:
      - nestjs-network
    restart: always
    environment:
      - TZ=UTC
    # deploy:
    #   mode: replicated
    #   replicas: 2
    #   update_config:
    #     parallelism: 1
    #     order: start-first
    #     delay: 10s
    #     failure_action: rollback

  nginx:
    image: nginx:stable-alpine
    container_name: omg-nginx
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - NGINX_PORT=80
      - BACKEND_PORT=8000
      - TZ=UTC
    ports:
      - 80:80
    depends_on:
      - api
    networks:
      - nestjs-network
networks:
  nestjs-network:
    driver: bridge
